version: '3.7'

services:

  api:
    container_name: meduzzen-backend-internship
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - api_network
    volumes:
      - .:/code
    command: >
      sh -c "uvicorn app.main:app --host ${HOST:-0.0.0.0} --port ${PORT:-5000} --reload"

  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_PORT}
      POSTGRES_SERVICE: ${DB_HOST}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - api_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - api_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - api_network
    volumes:
      - .:/code
    command: >
      sh -c "celery -A app.celery.celery worker --loglevel=warning --logfile=celery_worker.log"

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - api_network
    volumes:
      - .:/code
    command: >
      sh -c "celery -A app.celery.celery beat --loglevel=warning --logfile=celery_beat.log"

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - api_network
    volumes:
      - .:/code
    ports:
      - "5557:5555"
    command: >
      sh -c "celery flower --app=app.celery.celery --broker="${CELERY_BROKER_URL}""

volumes:
  postgres_data:

networks:
    api_network:
        driver: bridge