version: '3.7'

services:

  api:
    container_name: meduzzen-backend-internship
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - api_network
    volumes:
      - ./media:/code/media

  postgres:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_PORT}
      POSTGRES_SERVICE: ${DB_HOST}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - api_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - api_network


volumes:
  postgres_data:

networks:
    api_network:
        driver: bridge