version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    network_mode: bridge

  postgres:
    image: postgres:14.0-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    network_mode: bridge
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_PORT}
      POSTGRES_SERVICE: ${DB_HOST}

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    network_mode: bridge

volumes:
  postgres_data:
  redis_data:
