version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    network_mode: bridge

  postgres:
    image: postgres:14.0-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    network_mode: bridge

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    network_mode: bridge

volumes:
  postgres_data:
  redis_data:
