"""added is_active flag

Revision ID: e3dca41f866e
Revises: a69c3d731bb3
Create Date: 2024-05-01 14:22:19.080615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dca41f866e'
down_revision: Union[str, None] = 'a69c3d731bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_quiz_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'quizzes', ['quiz_id'], ['id'], ondelete='SET NULL')
    op.add_column('quizzes', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'is_active')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_quiz_id_fkey', 'questions', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
