"""removed is_admin field from user model

Revision ID: a34edb4583ae
Revises: 59e119cfbe95
Create Date: 2024-04-30 12:04:48.873709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34edb4583ae'
down_revision: Union[str, None] = '59e119cfbe95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_company_uc', 'company_members', ['user_id', 'company_id'])
    op.drop_constraint('company_members_company_id_fkey', 'company_members', type_='foreignkey')
    op.drop_constraint('company_members_user_id_fkey', 'company_members', type_='foreignkey')
    op.create_foreign_key(None, 'company_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'company_members', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_members', type_='foreignkey')
    op.drop_constraint(None, 'company_members', type_='foreignkey')
    op.create_foreign_key('company_members_user_id_fkey', 'company_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('company_members_company_id_fkey', 'company_members', 'companies', ['company_id'], ['id'])
    op.drop_constraint('_user_company_uc', 'company_members', type_='unique')
    # ### end Alembic commands ###
